project:
  type: website

website:
  title: "Tyler Johnston"
  description: "Resume of Tyler Johnston."
  navbar:
    title: "Tyler Johnston"
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css
    include-in-header:
      - text: <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">



